###index
GET http://prefa.test/api/postulantes 

###store
POST http://prefa.test/api/postulantes 
Accept: application/json
Content-Type: application/json

{
    "user_id": "5",
    "carnet": "12345",
    "nombre": "juan",
    "genero": "masculino",
    "fecha_nacimiento": "1996-03-19",
    "correo": "jos123apaza@gmail.com",
    "fecha_pago": "2024-05-20 10:05:25",
    "imagen": ""
}

###show
GET http://prefa.test/api/postulantes/16

###update
PUT http://prefa.test/api/postulantes/16
Accept: application/json
Content-Type: application/json

{
    "user_id": 2,
    "carnet": "54321",
    "nombre": "ana actualizado",
    "genero": "femenino",
    "fecha_nacimiento": "20-05-2000"
}

###destroy
DELETE http://prefa.test/api/postulantes/16
